spring:

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/java-task15
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  error:
    include-message: always

logging:
  path: spring/logs